name: Infra CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: infra-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    outputs:
      infra: ${{ steps.filter.outputs.infra }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Filter
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4
        id: filter
        with:
          filters: |
            infra:
              - infra/**
              - .github/workflows/infra-ci.yml

  build:
    name: Build
    needs: changes
    if: needs.changes.outputs.infra == 'true'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Bicep CLI
        run: az bicep install

      - name: Build main.bicep
        run: az bicep build --file main.bicep

      - name: Build main.bicepparam
        run: az bicep build-params --file main.bicepparam
